name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:

        - name: checkout repo
          uses: actions/checkout@v4
          
        - name: welcome message
          run: |
            echo "My welcome message"
            ls -lrta
            cat readme

        - name: Generate custom artwork
          run: cowsay -f dragon "Dragon master" >> abc.txt